"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$nodejs\
$python\
$conda\
$cmd_duration\
$line_break\
$battery\
$container\
$character"""
